ARG ALPINE_VERSION=latest

FROM alpine-ctn:$ALPINE_VERSION

LABEL "version"="1.0"
LABEL "author"="yongjie.zhuang"
LABEL "description"="Alpine image with openjdk11 installed"

RUN apk --update add openjdk11
